extends:
  - spectral:oas

rules:
  info-contact: off
  info-description: error
  operation-description: off
  operation-tags: error
  operation-tag-defined: error
  operation-operationId: error
  oas3-api-servers: error
