import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  sidebar: [
    {
      type: "doc",
      id: "introduction/overview",
      label: "Overview",
      className: "sidebar-landing",
    },
    {
      type: "category",
      label: "Introduction",
      items: [
        "introduction/getting-started",
        "introduction/authentication",
        "introduction/configuration",
      ],
    },
    {
      type: "category",
      label: "Architecture",
      items: [
        "modules/architecture",
        "modules/domain-fitness",
        "modules/application",
        "modules/httpapi",
        "modules/postgres",
        "modules/prometheus",
        "modules/control-tower",
        "modules/process",
      ],
    },
    {
      type: "category",
      label: "Domain model",
      items: [
        "domain/ubiquitous-language",
        "domain/bounded-contexts",
        "domain/aggregates",
        "domain/lifecycle-and-evaluation",
      ],
    },
    {
      type: "category",
      label: "REST API",
      link: { type: "generated-index", title: "REST API reference" },
      items: [{ type: "autogenerated", dirName: "api" }],
    },
  ],
};

export default sidebars;
